### ISSUE TITLE
Some more help in the README... 

### ISSUE THREAD

**Issue by ebullient** [JirkaDellOro/FreeMindViewer#2]
In the README, would like some help with what version of php this requires, and how I would specify (via js route or php route) which map it should render (where the map is in the data directory).

A sample map in the data/lib directory would be useful to explain how things hang together.

(Thanks for the LICENSE file.. this is the closest that I've found to something that I need. So if I can get this working, I will absolutely contribute back)

**Comment by JirkaDellOro** [comment]
Hi Erin,
I updated the README, it was outdated. PHP is not required any more and the data-folder is going to be deleted. I created a small README.mm that is going to be loaded if you load index.html without parameters. You should get it going without any problems. Please tell me if this is not the case.

**Comment by ebullient** [comment]
Yes! Thanks. I did figure it out, but the confirmation and the example are very helpful, thanks!

**Comment by ebullient** [comment]
Fixed by 75413ba40abff1bc6acd955fbc87a80b5d1bbd68
